/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.SwingUtilities;

/**
 *
 * @author laura
 */
public class TelaLivro extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLivro() {
        initComponents();
        btnVoltar.setName("btnVoltar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        reservar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Harry Potter - 3.2-.jpeg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel7PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(30, 80, 150, 230);

        Titulo1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(153, 0, 255));
        Titulo1.setText("E O PRISIONEIRO DE AZKABAN");
        getContentPane().add(Titulo1);
        Titulo1.setBounds(110, 50, 450, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Autor:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 90, 50, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Status:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 120, 60, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Categoria:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 150, 80, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Sinopse:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 180, 60, 16);

        Titulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(102, 0, 204));
        Titulo.setText("HARRY POTTER ");
        getContentPane().add(Titulo);
        Titulo.setBounds(140, 10, 640, 43);

        jLabel9.setText("J. K. Rowling");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 90, 70, 20);

        reservar.setText("Indisponível");
        getContentPane().add(reservar);
        reservar.setBounds(270, 110, 70, 40);

        jLabel11.setText("Fantástica Juvenil");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(290, 150, 100, 20);

        jLabel6.setText("está no terceiro ano na Escola de Magia e Bruxaria de Hogwarts. ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 220, 380, 20);

        jLabel12.setText("Juntamente com Rony e Hermione, seus melhores amigos, Harry Potter ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(200, 190, 380, 40);

        jLabel13.setText("Os assustadores guardas da prisão de Azkaban foram chamados para ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(190, 240, 380, 16);

        jLabel14.setText("vigiar as entradas da escola, pois um perigoso assassino está foragido ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(190, 260, 380, 16);

        jLabel15.setText("e tudo indica que o seu alvo é o herdeiro de Lílian e Tiago Potter. ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(190, 280, 390, 16);

        jLabel16.setText("O que acontecerá com Harry diante desta ameaça?");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(190, 300, 320, 16);

        btnReservar.setBackground(new java.awt.Color(59, 31, 112));
        btnReservar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReservar.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar.setText("Comprar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservar);
        btnReservar.setBounds(240, 340, 160, 40);

        btnVoltar.setBackground(new java.awt.Color(59, 31, 112));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(20, 370, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed

  
        // Mostra o erro no console
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        /*TelaCatalogo telaCatalogo = new TelaCatalogo();
    
    telaCatalogo.setVisible(true);
    
    this.dispose();*/
        
        SwingUtilities.invokeLater(() -> {
        TelaCatalogo telaCatalogo = new TelaCatalogo();
        telaCatalogo.setVisible(true);
    });

    javax.swing.Timer timer = new javax.swing.Timer(400, e -> this.dispose());
    timer.setRepeats(false);
    timer.start();

    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jLabel7PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel7PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>]
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel reservar;
    // End of variables declaration//GEN-END:variables

   
}
