package Telas;
import modelo.*;
import java.sql.*;
import javax.swing.JOptionPane;
import Telas.TelaCadastro;
import Telas.TelaCatalogo;
import Telas.TelaLogin;
import modelo.Conexao;
import javax.swing.JOptionPane;

import javax.swing.*;
import java.awt.event.*;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author laura
 */
public class TelaLogin extends javax.swing.JFrame {

    static String getText() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public static String trim() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form TelaLivro
     */
    public TelaLogin() {
        initComponents();
         Email.setName("Email");
    Senha.setName("Senha");
    
    btnEntrar.setName("btnEntrar");
    btnDeletar.setName("btnDeletar");
    btnAdministrador.setName("btnAdministrador");
    btnCadastrar.setName("btnCadastrar");
    btnAtualizar.setName("btnAtualizar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Senha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        btnAdministrador = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 255));
        jLabel3.setText("Senha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 210, 90, 50);

        Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaActionPerformed(evt);
            }
        });
        getContentPane().add(Senha);
        Senha.setBounds(260, 220, 230, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 255));
        jLabel2.setText("Email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 160, 90, 50);

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Email);
        Email.setBounds(260, 170, 230, 30);

        btnAdministrador.setBackground(new java.awt.Color(198, 186, 255));
        btnAdministrador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministrador.setText("Administrador");
        btnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdministrador);
        btnAdministrador.setBounds(490, 330, 140, 30);

        btnDeletar.setBackground(new java.awt.Color(198, 186, 255));
        btnDeletar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar);
        btnDeletar.setBounds(510, 270, 110, 40);

        btnAtualizar.setBackground(new java.awt.Color(198, 186, 255));
        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(360, 270, 120, 40);

        btnCadastrar.setBackground(new java.awt.Color(198, 186, 255));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(220, 270, 120, 40);

        btnVoltar.setBackground(new java.awt.Color(198, 186, 255));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(20, 330, 90, 30);

        btnEntrar.setBackground(new java.awt.Color(198, 186, 255));
        btnEntrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(110, 270, 90, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 70, 120, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        TelaInicial telaInicial = new TelaInicial();
    
    telaInicial.setVisible(true);
    
    this.dispose();  
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
    
    String email = Email.getText();
    String senha = Senha.getText(); 
    
       //Coloquei ontem o preencimento obrigatório dos campos 
    if (email.trim().isEmpty() || senha.trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Preencha o e-mail e a senha para continuar.");
    return;
}


    try {
        Connection conexao = Conexao.conectar();
       String sql = "SELECT * FROM Usuario WHERE Email = ? AND Senha = ?";
        PreparedStatement stmt = conexao.prepareStatement(sql);
        stmt.setString(1, email);
        stmt.setString(2, senha);

        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Login realizado com sucesso!");
            TelaCatalogo TelaCatalogo = new TelaCatalogo();
            TelaCatalogo.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Email ou senha inválidos.");
        }

        conexao.close();
    } catch (SQLException erro) {
        JOptionPane.showMessageDialog(this, "Erro ao tentar logar: " + erro.getMessage());
    }
    
   /* TelaCatalogo telaCatalogo = new TelaCatalogo();
    
    telaCatalogo.setVisible(true);
    
    this.dispose();*/
    
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        String email = Email.getText().trim();

               if (email.isEmpty()) {
                   JOptionPane.showMessageDialog(null, "Informe o e-mail do usuário que deseja deletar.");
                   return;
               }

               int confirmacao = JOptionPane.showConfirmDialog(null,
                       "Tem certeza que deseja excluir o usuário com e-mail: " + email + "?",
                       "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);

               if (confirmacao == JOptionPane.YES_OPTION) {
                   try {
                       try (Connection conexao = Conexao.conectar()) {
                           String sql = "DELETE FROM Usuario WHERE Email = ?";
                           PreparedStatement stmt = conexao.prepareStatement(sql);
                           stmt.setString(1, email);
                           
                           int linhasAfetadas = stmt.executeUpdate();
                           
                           if (linhasAfetadas > 0) {
                               JOptionPane.showMessageDialog(null, "Usuário deletado com sucesso!");
                           } else {
                               JOptionPane.showMessageDialog(null, "Usuário não encontrado.");
                           }
                       }
                   } catch (SQLException erro) {
                       JOptionPane.showMessageDialog(null, "Erro ao deletar usuário: " + erro.getMessage());
                   }
               }
       
    
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradorActionPerformed
        // TODO add your handling code here:
        
      boolean usuarioCadastrado = Email.getText().trim().isEmpty();
        if (usuarioCadastrado) {
    // Se o usuário já foi cadastrado, abrir TelaLogin
       TelaAdm telaAdm = new TelaAdm();
       telaAdm.setVisible(true);
       this.dispose();
} else {
    // Se ainda não foi cadastrado, abrir TelaCadastro
    TelaCadastro telaCadastro = new TelaCadastro();
    telaCadastro.setVisible(true);
    this.dispose();
}


    }//GEN-LAST:event_btnAdministradorActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        TelaCadastro telaCadastro = new TelaCadastro();
    
    telaCadastro.setVisible(true);
    
    this.dispose(); 
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        String email = Email.getText().trim();
    String novaSenha = Senha.getText().trim();

    if (email.isEmpty() && novaSenha.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Informe o e-mail e/ou nova senha do usuário que deseja atualizar.");
        return;
    }

    int confirmacao = JOptionPane.showConfirmDialog(null,
            "Tem certeza que deseja atualizar os dados do usuário com e-mail: " + email + "?",
            "Confirmar Atualização", JOptionPane.YES_NO_OPTION);

    if (confirmacao == JOptionPane.YES_OPTION) {
        try {
            try (Connection conexao = Conexao.conectar()) {
                String sql = "UPDATE Usuario SET Senha = ? WHERE Email = ?";
                PreparedStatement stmt = conexao.prepareStatement(sql);
                stmt.setString(1, novaSenha);
                stmt.setString(2, email);
                
                int linhasAfetadas = stmt.executeUpdate();
                
                if (linhasAfetadas > 0) {
                    JOptionPane.showMessageDialog(null, "Usuário atualizado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Usuário não encontrado.");
                }
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao atualizar usuário: " + erro.getMessage());
        }
    }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Senha;
    private javax.swing.JButton btnAdministrador;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
